### ISSUE TITLE
Technical replicates

### ISSUE THREAD

**Issue by andrewlai** [ftwkoopmans/msdap#16]
Hi,

Great software!

I was wondering how do I flag technical replicates in the sample metadata before performing Differential abundance analysis.

Thanks

**Comment by ftwkoopmans** [comment]
Commonly used approaches to dealing with technical replicates; 
1) account for technical replicates in the statistical model
2) preprocess the proteomics dataset by merging peptide abundance values among technical replicates prior to downstream analyses

To apply the former, you can add random variables to the DEqMS and MSqRob linear regression models in MS-DAP using the 'random_variables' parameter in the setup_contrasts() function. Example; `dataset = setup_contrasts(dataset, contrast_list = list(c("control","disease")), random_variables = "patient")` (assuming that 'patient' is a column in your sample metadata & this "groups" your technical replicates / repeated measurements of the same individual). 

Approach (2) is not a built-in feature of MS-DAP yet, but will be included in the upcoming release (which'll probably go public in September).

Making the right choice between both approaches depends on your experimental design and dataset; please consult your lab's statistician.

**Comment by ftwkoopmans** [comment]
release 1.0.6 is now live and includes a function for merging technical replicates right after importing the data (i.e. prior to any filtering/normalizing/stats). After updating MS-DAP (instructions on main MS-DAP GitHub page), see help page for the new `merge_replicate_samples()` function  (e.g. by issuing the R command `?merge_replicate_samples` , after installing the updated R package)

**Comment by andrewlai** [comment]
Awesome. Thanks for the great work!
