### ISSUE TITLE
Error in Summarise_stats

### ISSUE THREAD

**Issue by medsoccer** [ftwkoopmans/msdap#17]
Hi trying to get The DEA summary but keep getting the below error:

Error in summarise_stats(dataset, return_dea = TRUE, return_diffdetect = TRUE,  : 
  could not find function "summarise_stats"

**Comment by ftwkoopmans** [comment]
The `summarise_stats` function has been introduced with the recent MS-DAP 1.0.6 release. If you haven't already, please upgrade your msdap package and see if that resolves the issue. To update;

- close RStudio if opened
- open RStudio
- run the following code snippet to update msdap and only the minimum set of dependencies / other R packages (you can replace `upgrade="never"` with `upgrade="always"` to update all dependencies if you want)
```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```

you can confirm the installed MS-DAP version by checking the 'Packages' pane in RStudio or by using the R command; `msap::msdap_version()`

**Comment by medsoccer** [comment]
That worked well, thanks so much for the update.
