### ISSUE TITLE
Log2fold or ratio

### ISSUE THREAD

**Issue by medsoccer** [ftwkoopmans/msdap#18]
Hi, in the output file for the differential proteins is the log2fold change that or is it a log ratio?

**Comment by ftwkoopmans** [comment]
I'm not entirely sure what you are asking.

The output file "differential_abundance_analysis.xlsx" contains log2 foldchanges, as indicated by the column names and legends. 

For example, if you performed differential expression analysis using DEqMS for the contrast "A vs B" then the output table will contain a column named "foldchange.log2_deqms_contrast: A vs B"

The legends included in this Excel file confirm this as well. Quote:
> For each statistical model applied (DEqMS, MSqRob, etc.), the log2 foldchange, pvalue and qvalue (pvalue adjusted for multiple testing) are provided.
> Note that a MS-DAP contrast for "A vs B" returns foldchanges for B/A. For example, for the contrast "control vs disease" a positive log2 foldchange implies protein abundances are higher in the "disease" sample group.
