### ISSUE TITLE
Volcanos Plot

### ISSUE THREAD

**Issue by camymhe** [ftwkoopmans/msdap#23]
Hello... is it possible to get a list of up and down-regulated proteins? Didn't quite understand that part in the report.

Appreciate the help.

**Comment by ftwkoopmans** [comment]
If you follow the example on [on the main page](https://github.com/ftwkoopmans/msdap) you can see how to setup statistical contrasts (e.g. to test for differences between WT and KO conditions). Following this example, the output folder will contain a "report.pdf" file that contains volcano plots which visualize the differential expression analysis (DEA) results and a "differential_abundance_analysis.xlsx" file that contains all DEA stats in Excel format.
