### ISSUE TITLE
Enrichment using DD proteins 

### ISSUE THREAD

**Issue by AhadAbdalla** [ftwkoopmans/msdap#24]
Hi and thanks again for a great package. I know you mentioned previously you would use the list of differentially detected proteins qualitatively in enrichment analysis, My question is how you would if possible this list in something like GSEA as you would need a logfold change and pvalue?

**Comment by ftwkoopmans** [comment]
For GSEA all you need are effectsizes or foldchanges, you don't need both a log2fc and p-value. Having said that, in our lab we never use only the differential-detect statistics but instead we primarily rely on differential expression analysis (DEA, e.g. deqms/msqrob/msempire) and then optionally supplement those results with strong hits from the differential detection metric.

I would advice against using only differential detection for GSEA, it is known that DEA is much more powerful. i.e. the extremes observed by differential detection are useful and this information might be exclusive to DD, but this metric is less informative (than DEA) for a huge proportion of proteins. For most datasets I follow the workflow shown in the [summarizing results from statistics + gene ID mapping](https://github.com/ftwkoopmans/msdap/blob/master/doc/stats_summary.md) vignette. 

- run the `analysis_quickstart()` function as per usual
- check the plots for the differential detection to determine what cutoff we consider for "interesting candidates from DD"
- run the `summarise_stats()` function (as described in the vignette linked above)
- use the unified table with statistics results for GO analyses

**Comment by AhadAbdalla** [comment]
Thanks yep I was planning on using both lists, I guess my question was about how to rank them but I'll run the function and see what effect sizes are given to the DD list. Unfortunately the data file crashes R each time as its about 6gb in size even though I'm running on decent RAM.
