### ISSUE TITLE
error in plot_peptide_data

### ISSUE THREAD

**Issue by jd690764** [ftwkoopmans/msdap#27]
Hi,

I am trying to use the plot_peptide_data function but I am always getting an error:

> msdap::plot_peptide_data(dataset, select_all_proteins = F, select_dea_signif = T, output_dir = file.path(output_dir, 'profiles'), norm_algorithm = c("vwmb", "modebetween_protein"), show_unused_datapoints = T)
info: while visualizing peptide-level data per protein, 'reintroduced' datapoints lost during filtering were normalized by; vwmb&modebetween_protein
progress: peptide to protein rollup with MaxLFQ (implementation: iq) took 1 seconds
info: using 11 threads for multiprocessing
Error in `mutate()`:
ℹ In argument: `algorithm = paste0("zscore", type, "counts")`.
Caused by error in `as.vector()`:
! cannot coerce type 'closure' to vector of type 'character'
Run `rlang::last_trace()` to see where the error occurred.
There were 22 warnings (use warnings() to see them)
> rlang::last_trace()
<error/dplyr:::mutate_error>
Error in `mutate()`:
ℹ In argument: `algorithm = paste0("zscore", type, "counts")`.
Caused by error in `as.vector()`:
! cannot coerce type 'closure' to vector of type 'character'
---
Backtrace:
     ▆
  1. ├─msdap::plot_peptide_data(...)
  2. │ └─msdap:::plot_peptide_data_by_contrast_to_pdf(...)
  3. │   └─tib_dd %>% select(protein_id, foldchange = zscore) %>% ...
  4. ├─dplyr::mutate(., algorithm = paste0("zscore", type, "counts"))
  5. ├─dplyr:::mutate.data.frame(., algorithm = paste0("zscore", type, "counts"))
  6. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  7. │   ├─base::withCallingHandlers(...)
  8. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
  9. │     └─mask$eval_all_mutate(quo)
 10. │       └─dplyr (local) eval()
 11. └─base::paste0("zscore", type, "counts")
 12.   ├─base::as.character(`<stndrdGn>`)
 13.   └─base::as.character.default(`<stndrdGn>`)
Run rlang::last_trace(drop = FALSE) to see 3 hidden frames.

I tried various ways of calling the function but I always get this same error.

Could you please look into this?

Thank you,
Janos

**Comment by ftwkoopmans** [comment]
Thanks for reporting. I am currently traveling and will look into this issue in approx. 1 week

**Comment by ftwkoopmans** [comment]
This issue should be resolved in the latest release, please update to MS-DAP 1.0.8

Run this R snippet in a clean R session (i.e. restart RStudio if it is running) to update
```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```

**Comment by jd690764** [comment]
THank you! It is working now.
Janos
