### ISSUE TITLE
Support DIA-NN 1.9's parquet report format

### ISSUE THREAD

**Issue by sooheon** [ftwkoopmans/msdap#34]
Since 1.9, DIA-NN outputs a parquet file by default, which has essentially the same data as the old tsv report, just in a much more space efficient format. IME it's ~10x space savings, so worth adding support.

**Comment by ftwkoopmans** [comment]
Good idea, I'll add support in the next release.

**Comment by ftwkoopmans** [comment]
I've just uploaded [release 1.1.3](https://github.com/ftwkoopmans/msdap/releases/tag/1.1.3) which can read DIA-NN reports in parquet format. Just use the `import_dataset_diann()` function as per usual, with the filename parameter set to (full file path to) the "report.parquet" file.

After starting a fresh RStudio session, run the following code snippet to update the MS-DAP R package and only the minimum set of dependencies (you can replace upgrade="never" with upgrade="always" to update all dependencies if you want)

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```
