### ISSUE TITLE
gene symbol capitalization

### ISSUE THREAD

**Issue by jd690764** [ftwkoopmans/msdap#35]
Hi,

during fasta import in import_fasta(), gene symbols are capitalized. This is not correct for e.g. mouse and causes problems with using these gene symbols later on. 

Is there a way to keep the original symbols the way they appear in the fasta file?

Thank you,
Janos

**Comment by ftwkoopmans** [comment]
You may use case-insensitive matching in downstream use of MS-DAP output; I am not aware of any genes where this would lead to false positive matches.

For example, mouse gene Dlg4 (MGI:1277959) is the same gene as Hunan gene DLG4 (HGNC:2903). Or vice versa; I am not aware of any examples where official gene symbols mismatch by case, e.g. "abcde1" in species A is not the same gene as "ABCDE1" in species B.

Regardless, I will add this feature request to the TODO list and ping back here when completed.

**Comment by ftwkoopmans** [comment]
I've just uploaded [release 1.1.3](https://github.com/ftwkoopmans/msdap/releases/tag/1.1.3) which has a new option to preserve gene symbol case from the FASTA.

In the `import_fasta()` function, setting `uppercase_symbols = FALSE` should resolve the above issue.

After starting a fresh RStudio session, run the following code snippet to update the MS-DAP R package and only the minimum set of dependencies (you can replace upgrade="never" with upgrade="always" to update all dependencies if you want)

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```
