### ISSUE TITLE
Support different columns for sample contrasts

### ISSUE THREAD

**Issue by sooheon** [ftwkoopmans/msdap#37]
I think it's common to want different granularity for contrasts, so if any column can be used for contrast creation that would help. 

Another nice feature would be to have "X vs. other" contrasts (i.e. if variable "Source" has values "brain", "breast", "lung", contrast "lung" vs other.

**Comment by ftwkoopmans** [comment]
Coincidentally, the features you describe have been in development for quite some time and are now available in a new MS-DAP release.

As described in the release notes of version 1.2 https://github.com/ftwkoopmans/msdap/releases/tag/1.2 
you can use the new `add_contrast()` function to create statistical contrasts as desired: you can now use 'any' column in the samples table to define contrasts and use `NA` as the second group's definition to indicate "all values not in group1". After installing the update, use `?add_contrast()` to view the documentation/examples.



To update MS-DAP to the latest version: after starting a fresh RStudio session, run the following code snippet to update the MS-DAP R package and only the minimum set of dependencies (you can replace upgrade="never" with upgrade="always" to update all dependencies if you want)

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```
