### ISSUE TITLE
Is it possible to do paired differential expression analysis in MSDAP?

### ISSUE THREAD

**Issue by SongbiaoZhu** [ftwkoopmans/msdap#38]
Hi, thanks for your fantastic work. I have paired samples, which are commonly analyzed with paired t-test. Now I am using the MSDAP, how to set the paired parameter in DeqMS, MSqRob, MS-EmpiRe? I am using the analysis_quick_start function, in which I did not see the parameter. Looking forward for your reply.

**Comment by ftwkoopmans** [comment]
The MS-EmpiRe method does not support any additional regression variables (i.e. it's strictly A/B testing). 

To add additional regression variables to your analysis, e.g. to effectively do a linear regression with formula 
"intensity ~ condition + block", you can add additional regression variables for ebayes/deqms/msqrob when
setting up your contrasts with `setup_contrasts()` using the parameter
`random_variables` (you can provide column names from your sample metadata table).

Additionally, in the new MS-DAP version 1.2 you have full flexibility to create any regression model using 
limma. But note that this flexibility comes at the cost of some additional programming / complexity as compared to default MS-DAP workflows.
Check out the documentation at: https://github.com/ftwkoopmans/msdap/blob/master/doc/custom_limma.md


To update MS-DAP to the latest version: after starting a fresh RStudio session, run the following code snippet to update the MS-DAP R package and only the minimum set of dependencies (you can replace upgrade="never" with upgrade="always" to update all dependencies if you want)

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```
