### ISSUE TITLE
removing decoy proteins and contaminants from the final data report

### ISSUE THREAD

**Issue by kamalmdmostafa** [ftwkoopmans/msdap#39]
It would be helpful to have the option to remove decoy tags, such as "rev_XXX," and contaminants from the cRAP database if they were included in the FASTA database during analysis.

**Comment by ftwkoopmans** [comment]
There's been a recent update to MS-DAP that causes the `import_fasta()` function to recognize and remove
decoy proteins when importing fasta files (see below for update instructions).
If you are using a MS-DAP version that is _lower_ than 1.1.2, please update MS-DAP first.

If you have a fasta database that has "rev_" or "decoy_" tags that are not correctly imported when using the latest MS-DAP, please share your data (i.e. DIA-NN/MaxQuant/etc. output) and fasta files (via dropbox/wetransfer) and I will investigate.

We never use the cRAP database so I'm not sure if those proteins have some kind of recognisable tag.
However, if they do you can use MS-DAP function `remove_proteins_by_name()` (_after_ running `import_dataset_diann()` and `import_fasta()`) to match a regular expression against the fasta headers and remove respective proteins from the dataset.

To update MS-DAP to the latest version: after starting a fresh RStudio session, run the following code snippet to update the MS-DAP R package and only the minimum set of dependencies (you can replace upgrade="never" with upgrade="always" to update all dependencies if you want)

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```

**Comment by kamalmdmostafa** [comment]
Thank you so much; I did not notice the update. I have been using MSDAP for all my DIA-NN analyses. I will try the latest version and your suggestions and let you know if I need help. 
The DIA-NN v1.9 (latest) has the option to add contaminant, and it adds the cRAP database, and the tags are, for example, "cRAP-O43790" for Keratin.

**Comment by ftwkoopmans** [comment]
To follow-up on this: I just used DIA-NN 1.9.1 to analyze 2 random raw files and provided as FASTA files
both the full uniprot Human proteome (canonical and additional files) and check the "Contaminants"
box to include the cRAP proteins.

Here's how I then used MS-DAP 1.2 to:

1. import the DIA-NN dataset as per usual
2. import the Human proteome and the cRAP FASTA that is bundled with DIA-NN
3. remove these cRAP proteins, if so desired


```
library(msdap)
dataset = import_dataset_diann(filename = "D:/temp/report.parquet")

# you can import the cRAP FASTA file together with the actual proteome FASTA used in DIA-NN
dataset = import_fasta(dataset, files = c(
  "C:/VU/fasta/uniprot/2020_04/UP000005640_9606.fasta",
  "C:/VU/fasta/uniprot/2020_04/UP000005640_9606_additional.fasta",
  "C:/DIA-NN/1.9.1/camprotR_240512_cRAP_20190401_full_tags.fasta"
))

# if you want to remove all the cRAP proteins up-front, you can completely remove 
# them from the dataset using a regular expression matched against FASTA headers
dataset = remove_proteins_by_name(dataset, regular_expression = "sp\\|cRAP-")
```
