### ISSUE TITLE
0 proteingroups mapped

### ISSUE THREAD

**Issue by benj-sic** [ftwkoopmans/msdap#41]
From msdap::export_stats_genesummary: "info: 0 / 5310 (0.0%) proteingroups were successfully mapped to 0 unique human genes. 274 / 432 ambiguous proteingroups had a leading gene symbol that overlapped with an unambiguous proteingroup"

My exported results only have protein_id (e.g., Q99715). My dataset is DIA-NN.

I notice that hgnc_lookuptable does not have protein_id.

Is there a way to map protein_id to hgnc_id, symbol, ensembl_id, and entrez_id?

**Comment by benj-sic** [comment]
The issue was with the fasta file. It's mapping fine now. My apologies.

**Comment by ftwkoopmans** [comment]
no worries, I'm glad it all worked out
