### ISSUE TITLE
Question concerning statistics

### ISSUE THREAD

**Issue by lananh-ngn** [ftwkoopmans/msdap#6]
Hello,
Thank you again for developing this tool. After running the tool, there are some rows with empty fold changes in differential_abundance_analysis.xlsx. In the two conditions I am testing, the protein is not detected in one but is detected in the other. Is it the reason why?
Thank you in advance,
Best regards,
Lan Anh

**Comment by ftwkoopmans** [comment]
Only the subset of peptides that pass the filtering rules, as configured in the `analysis_quickstart()` function (e.g. `filter_min_detect` and `filter_min_quant`), are used in differential expression analyses (DEA). Consequently, some proteins will not be used for DEA and thus have no foldchange/pvalue in the output Excel table.

To look at proteins that have a strong difference in detection between experimental conditions, you may look at the "zscore" columns in the output Excel table (brief explaination of this score can be found on the 'legend' sheet of the same Excel table). For instance, in some studies we perform GO analyses on MS-DAP results by combining all significant proteins from DEA and proteins that have an absolute value >= 3 in the differential detection z-score.
