### ISSUE TITLE
Calculating the contrast of two genotypes "vs"

### ISSUE THREAD

**Issue by akila-wijerathna-yapa** [ftwkoopmans/msdap#9]
When calculating contrast, this package use

```r
dataset = setup_contrasts(dataset, contrast_list = list(  c("WT","KO")  ) ) 

```
And its output volcano graphs labelled as "Contrast WT vs KO"

When this graph title says "vs" in what context its been used?
When we say A vs B; generally, we assume A ÷ B 

Here in this volcano plot contrast: WT vs KO, do you mean to say your reference is KO or vice versa (i.e WT)?
Are these red-color triangles (proteins) more abundant in WT or KO?

Can you help me to understand how this calculation function works please.

for e.g. https://www.nature.com/articles/s41598-021-82533-5

**Comment by ftwkoopmans** [comment]
This is described in the documentation that is included in the MS-DAP report.pdf file, same section as the volcano plots (provided you're using MS-DAP version 1.0.3). On the first page of the "differential abundance analysis" section it should read:

> contrasts and foldchanges
> Note that a MS-DAP contrast for “A vs B” returns foldchanges for B/A. For example, for the contrast “control vs disease” a positive log2 foldchange implies protein abundances are higher in the “disease” sample group.

As previously brought up in GitHub issue #5 , MS-DAP foldchange computation behaviour is documented in;
- report.pdf , at the start of the "Differential abundance analysis" section
- differential_abundance_analysis.xlsx , in the table legends on sheet 1
- setup_contrasts() R function documentation
- dea() R function documentation

ps. on GitHub you can browse 'closed' issues to see if any of your questions was previously raised and answered
